name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # or main, depending on your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a Node.js version compatible with your project

      - name: Install dependencies (client) 
        run: npm install
        working-directory: ./client

      - name: Build client 🏗️
        run: npm run build
        working-directory: ./client
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }} # Reemplaza con la URL de tu backend desplegado

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist
          publish_branch: gh-pages # The branch to deploy to
          cname: # Optional: if you have a custom domain, specify it here
